CREATE DATABASE IF NOT EXISTS JOBPORTAL;

USE JOBPORTAL;

CREATE TABLE IF NOT EXISTS LOGIN(USERNAME VARCHAR(255), 
                  PASSWRD VARCHAR(255), MAIL VARCHAR(255), 
                  PRIMARY KEY(USERNAME));

CREATE TABLE IF NOT EXISTS JOB_APPLICANT(USER_ID INT, USERNAME VARCHAR(255), FULLNAME VARCHAR(255), PHONE_NO VARCHAR(10), ADDRESS VARCHAR(255), MAIL_ID VARCHAR(255),
						   DOB date, PRIMARY KEY(USER_ID), FOREIGN KEY(USERNAME) REFERENCES LOGIN(USERNAME) ON DELETE CASCADE);
                            
CREATE TABLE IF NOT EXISTS EMPLOYER(EMP_ID INT, USERNAME VARCHAR(255), EMP_NAME VARCHAR(255), COMPANY VARCHAR(255), LOCATION VARCHAR(255),
                       PRIMARY KEY(EMP_ID), FOREIGN KEY(USERNAME) REFERENCES LOGIN(USERNAME) ON DELETE CASCADE);
                       
CREATE TABLE IF NOT EXISTS JOB_POSTINGS(JOB_ID INT, TITLE VARCHAR(1000), DESCR TEXT, PAY VARCHAR(1000), LOCATION VARCHAR(1000), EMP_ID INT, DATE_POSTED DATE, LAST_DATE DATE,
                          REQUIREMENTS TEXT, COMPANY VARCHAR(1000),
                          PRIMARY KEY(JOB_ID), FOREIGN KEY(EMP_ID) REFERENCES EMPLOYER(EMP_ID) ON DELETE CASCADE);
                          
                          
CREATE TABLE IF NOT EXISTS APPLICATION(APP_ID INT, JOB_ID INT, USER_ID INT, PDF_DATA LONGBLOB ,
                         STATUS VARCHAR(10), DOS DATE,
                         PRIMARY KEY(APP_ID), FOREIGN KEY (JOB_ID) REFERENCES JOB_POSTINGS(JOB_ID)ON DELETE CASCADE,
                         FOREIGN KEY(USER_ID) REFERENCES JOB_APPLICANT(USER_ID) ON DELETE CASCADE); 
                         
INSERT INTO LOGIN VALUES("RAJ1","123", "raj1@gmail.com"),("EMP1","123","emp1@gmail.com");

INSERT INTO JOB_APPLICANT VALUES(1,"RAJ1", "RAJ","1234567890","MUMBAI","RAJ@gmail.com","1990-04-23");

INSERT INTO EMPLOYER VALUES(1,"EMP1","RAGAV","ACCENTURE","BANGALORE");



INSERT INTO JOB_POSTINGS VALUES(1, "Software Developer", "Looking for Software developer", "12 Lakhs per Annum", "Bangalore",
                               1,"2023-01-12", "2023-02-14", "Minimum 2 years of Industry experience","ACCENTURE");
INSERT INTO JOB_POSTINGS VALUES(2, "Software Developer", "Looking for Software developer", "10 Lakhs PA","Remote",
                               1,"2023-01-12", "2023-02-14", "Minimum 2 years of Industry experience","INFOSYS");                               
                               